#!/usr/bin/env bash

set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/usb-mount-blocker"
BLOCKLIST_FILE="${CONFIG_DIR}/blocklist.tsv"
RULES_FILE="/etc/udev/rules.d/61-usb-mount-blocker.rules"
MEDIA_RULES_FILE="/etc/udev/rules.d/59-usb-mount-blocker-media.rules"
USBMUX_OVERRIDE_FILE="/etc/udev/rules.d/39-usbmuxd.rules"
LIBGPHOTO_OVERRIDE_FILE="/etc/udev/rules.d/60-libgphoto2-6t64.rules"
LIBMTP_OVERRIDE_FILE="/etc/udev/rules.d/69-libmtp.rules"
UACCESS_OVERRIDE_FILE="/etc/udev/rules.d/70-uaccess.rules"
COLORD_OVERRIDE_FILE="/etc/udev/rules.d/95-cd-devices.rules"
LIBGPOD_OVERRIDE_FILE="/etc/udev/rules.d/90-libgpod.rules"

declare -a DEVICE_KEYS=()
declare -a DEVICE_LABELS=()
declare -a DEVICE_STRATEGIES=()
declare -a DEVICE_MATCH_VALUES=()
declare -a DEVICE_RULE_NOTES=()
declare -a DEVICE_RULE_COUNTS=()
declare -a DEVICE_KINDS=()

print_header() {
    printf '\n== %s ==\n' "$1"
}

print_info() {
    printf '%s\n' "$1"
}

die() {
    printf 'Error: %s\n' "$1" >&2
    exit 1
}

require_commands() {
    local cmd
    for cmd in lsblk udevadm awk sed install mktemp; do
        command -v "$cmd" >/dev/null 2>&1 || die "Missing required command: $cmd"
    done
}

ensure_config() {
    mkdir -p "$CONFIG_DIR"
    if [ ! -f "$BLOCKLIST_FILE" ]; then
        cat > "$BLOCKLIST_FILE" <<'EOF'
# key	label	strategy	match_value	rule_count	note
EOF
    fi
}

extract_kv() {
    local line="$1"
    local key="$2"
    sed -n "s/.*${key}=\"\\([^\"]*\\)\".*/\\1/p" <<< "$line"
}

trim_spaces() {
    sed 's/^[[:space:]]*//; s/[[:space:]]*$//' <<< "$1"
}

lowercase() {
    tr '[:upper:]' '[:lower:]' <<< "$1"
}

read_sys_attr() {
    local path="$1"
    [ -f "$path" ] || return 0
    tr -d '\n' < "$path"
}

safe_label() {
    local text="$1"
    text="${text//$'\t'/ }"
    printf '%s' "$text"
}

run_as_root() {
    if [ "$(id -u)" -eq 0 ]; then
        "$@"
    elif command -v sudo >/dev/null 2>&1; then
        sudo "$@"
    else
        die "This action needs root privileges and sudo is not available."
    fi
}

read_blocklist_records() {
    awk -F '\t' 'NF >= 5 && $1 !~ /^[[:space:]]*#/ && $1 != "" { print }' "$BLOCKLIST_FILE"
}

device_exists_in_blocklist() {
    local key="$1"
    awk -F '\t' -v key="$key" '$1 == key { found=1 } END { exit(found ? 0 : 1) }' "$BLOCKLIST_FILE"
}

append_blocklist_record() {
    local key="$1"
    local label="$2"
    local strategy="$3"
    local match_value="$4"
    local rule_count="$5"
    local note="$6"

    printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$key" \
        "$(safe_label "$label")" \
        "$strategy" \
        "$match_value" \
        "$rule_count" \
        "$(safe_label "$note")" >> "$BLOCKLIST_FILE"
}

build_rules_file() {
    local temp_file
    temp_file="$(mktemp)"

    {
        printf '# Generated by usb_mount_blocker.sh\n'
        printf '# Blocks automatic mounting for selected USB storage devices.\n'
        printf '# Manual mounting remains possible.\n'
    } > "$temp_file"

    while IFS=$'\t' read -r key label strategy match_value rule_count note; do
        case "$strategy" in
            serial_short)
                printf 'SUBSYSTEM=="block", ENV{DEVTYPE}=="partition", ENV{ID_BUS}=="usb", ENV{ID_SERIAL_SHORT}=="%s", ENV{UDISKS_AUTO}="0"\n' "$match_value" >> "$temp_file"
                ;;
            serial)
                printf 'SUBSYSTEM=="block", ENV{DEVTYPE}=="partition", ENV{ID_BUS}=="usb", ENV{ID_SERIAL}=="%s", ENV{UDISKS_AUTO}="0"\n' "$match_value" >> "$temp_file"
                ;;
            fs_uuid)
                IFS=',' read -r -a uuids <<< "$match_value"
                local uuid
                for uuid in "${uuids[@]}"; do
                    [ -n "$uuid" ] || continue
                    printf 'SUBSYSTEM=="block", ENV{DEVTYPE}=="partition", ENV{ID_BUS}=="usb", ENV{ID_FS_UUID}=="%s", ENV{UDISKS_AUTO}="0"\n' "$uuid" >> "$temp_file"
                done
                ;;
            vendor_model)
                IFS='|' read -r vendor_id model_id <<< "$match_value"
                printf 'SUBSYSTEM=="block", ENV{DEVTYPE}=="partition", ENV{ID_BUS}=="usb", ENV{ID_VENDOR_ID}=="%s", ENV{ID_MODEL_ID}=="%s", ENV{UDISKS_AUTO}="0"\n' "$vendor_id" "$model_id" >> "$temp_file"
                ;;
            media_probe)
                printf '# Media device rule emitted in %s\n' "$MEDIA_RULES_FILE" >> "$temp_file"
                ;;
            *)
                printf '# Skipped unknown strategy for %s: %s\n' "$label" "$strategy" >> "$temp_file"
                ;;
        esac
    done < <(read_blocklist_records)

    printf '%s\n' "$temp_file"
}

read_media_records() {
    awk -F '\t' 'NF >= 5 && $1 !~ /^[[:space:]]*#/ && $3 == "media_probe" { print }' "$BLOCKLIST_FILE"
}

build_media_pre_rules_file() {
    local temp_file
    temp_file="$(mktemp)"

    {
        printf '# Generated by usb_mount_blocker.sh\n'
        printf '# Best-effort early media-device suppression.\n'
    } > "$temp_file"

    while IFS=$'\t' read -r key label strategy match_value rule_count note; do
        local vendor_id product_id serial_value
        IFS='|' read -r vendor_id product_id serial_value <<< "$match_value"

        if [ -n "$serial_value" ]; then
            printf 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="%s", ATTR{idProduct}=="%s", ATTR{serial}=="%s", ENV{MTP_NO_PROBE}="1", ENV{ID_MEDIA_PLAYER}="", ENV{ID_GPHOTO2}="", ENV{USBMUX_SUPPORTED}="0", ENV{COLORD_DEVICE}="0", ENV{COLORD_KIND}="", TAG-="uaccess"\n' \
                "$vendor_id" "$product_id" "$serial_value" >> "$temp_file"
        else
            printf 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="%s", ATTR{idProduct}=="%s", ENV{MTP_NO_PROBE}="1", ENV{ID_MEDIA_PLAYER}="", ENV{ID_GPHOTO2}="", ENV{USBMUX_SUPPORTED}="0", ENV{COLORD_DEVICE}="0", ENV{COLORD_KIND}="", TAG-="uaccess"\n' \
                "$vendor_id" "$product_id" >> "$temp_file"
        fi
    done < <(read_media_records)

    printf '%s\n' "$temp_file"
}

build_override_copy() {
    local source_file="$1"
    local target_kind="$2"
    local end_label="$3"
    local temp_file
    temp_file="$(mktemp)"

    {
        printf '# Generated by usb_mount_blocker.sh\n'
        printf '# Local override for %s\n' "$(basename "$source_file")"

        while IFS=$'\t' read -r key label strategy match_value rule_count note; do
            local vendor_id product_id serial_value
            IFS='|' read -r vendor_id product_id serial_value <<< "$match_value"

            case "$target_kind" in
                usbmuxd)
                    [ "$vendor_id" = "05ac" ] || continue
                    if [ -n "$serial_value" ]; then
                        printf 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="%s", ATTR{idProduct}=="%s", ATTR{serial}=="%s", GOTO="%s"\n' \
                            "$vendor_id" "$product_id" "$serial_value" "$end_label"
                    else
                        printf 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="%s", ATTR{idProduct}=="%s", GOTO="%s"\n' \
                            "$vendor_id" "$product_id" "$end_label"
                    fi
                    ;;
                libmtp)
                    if [ -n "$serial_value" ]; then
                        printf 'SUBSYSTEM=="usb", ATTR{idVendor}=="%s", ATTR{idProduct}=="%s", ATTR{serial}=="%s", ENV{MTP_NO_PROBE}="1", GOTO="%s"\n' \
                            "$vendor_id" "$product_id" "$serial_value" "$end_label"
                    else
                        printf 'SUBSYSTEM=="usb", ATTR{idVendor}=="%s", ATTR{idProduct}=="%s", ENV{MTP_NO_PROBE}="1", GOTO="%s"\n' \
                            "$vendor_id" "$product_id" "$end_label"
                    fi
                    ;;
                libgphoto2|libgpod|uaccess|colord)
                    if [ -n "$serial_value" ]; then
                        printf 'SUBSYSTEM=="usb", ATTR{idVendor}=="%s", ATTR{idProduct}=="%s", ATTR{serial}=="%s", GOTO="%s"\n' \
                            "$vendor_id" "$product_id" "$serial_value" "$end_label"
                    else
                        printf 'SUBSYSTEM=="usb", ATTR{idVendor}=="%s", ATTR{idProduct}=="%s", GOTO="%s"\n' \
                            "$vendor_id" "$product_id" "$end_label"
                    fi
                    ;;
            esac
        done < <(read_media_records)

        cat "$source_file"
        if [ "$target_kind" = "usbmuxd" ] || [ "$target_kind" = "colord" ]; then
            printf '\nLABEL="%s"\n' "$end_label"
        fi
    } > "$temp_file"

    printf '%s\n' "$temp_file"
}

install_or_remove_override() {
    local source_file="$1"
    local target_file="$2"
    local target_kind="$3"
    local end_label="$4"
    local needs_file="$5"

    if [ "$needs_file" != "true" ]; then
        run_as_root rm -f "$target_file"
        return 0
    fi

    [ -f "$source_file" ] || return 0

    local temp_file
    temp_file="$(build_override_copy "$source_file" "$target_kind" "$end_label")"
    run_as_root install -m 644 "$temp_file" "$target_file"
    rm -f "$temp_file"
}

install_rules() {
    ensure_config
    local temp_file media_temp_file media_count apple_media_count
    temp_file="$(build_rules_file)"
    run_as_root install -m 644 "$temp_file" "$RULES_FILE"
    rm -f "$temp_file"

    media_count="$(read_media_records | wc -l | tr -d ' ')"
    apple_media_count="$(read_media_records | awk -F '\t' '{
        split($4, parts, "|")
        if (parts[1] == "05ac") {
            count++
        }
    } END { print count + 0 }')"

    if [ "$media_count" -gt 0 ]; then
        media_temp_file="$(build_media_pre_rules_file)"
        run_as_root install -m 644 "$media_temp_file" "$MEDIA_RULES_FILE"
        rm -f "$media_temp_file"
    else
        run_as_root rm -f "$MEDIA_RULES_FILE"
    fi

    install_or_remove_override \
        "/lib/udev/rules.d/69-libmtp.rules" \
        "$LIBMTP_OVERRIDE_FILE" \
        "libmtp" \
        "libmtp_rules_end" \
        "$([ "$media_count" -gt 0 ] && printf true || printf false)"

    install_or_remove_override \
        "/lib/udev/rules.d/60-libgphoto2-6t64.rules" \
        "$LIBGPHOTO_OVERRIDE_FILE" \
        "libgphoto2" \
        "libgphoto2_rules_end" \
        "$([ "$media_count" -gt 0 ] && printf true || printf false)"

    install_or_remove_override \
        "/lib/udev/rules.d/90-libgpod.rules" \
        "$LIBGPOD_OVERRIDE_FILE" \
        "libgpod" \
        "libgpod_end" \
        "$([ "$apple_media_count" -gt 0 ] && printf true || printf false)"

    install_or_remove_override \
        "/lib/udev/rules.d/70-uaccess.rules" \
        "$UACCESS_OVERRIDE_FILE" \
        "uaccess" \
        "uaccess_end" \
        "$([ "$media_count" -gt 0 ] && printf true || printf false)"

    install_or_remove_override \
        "/lib/udev/rules.d/95-cd-devices.rules" \
        "$COLORD_OVERRIDE_FILE" \
        "colord" \
        "cd_dev_end" \
        "$([ "$media_count" -gt 0 ] && printf true || printf false)"

    install_or_remove_override \
        "/lib/udev/rules.d/39-usbmuxd.rules" \
        "$USBMUX_OVERRIDE_FILE" \
        "usbmuxd" \
        "usbmuxd_blocklist_end" \
        "$([ "$apple_media_count" -gt 0 ] && printf true || printf false)"

    run_as_root udevadm control --reload-rules
    print_info "Updated rules: $RULES_FILE"
    if [ "$media_count" -gt 0 ]; then
        print_info "Updated media rules: $MEDIA_RULES_FILE"
    fi
    print_info "Reloaded udev rules."
}

collect_partition_details() {
    local disk_name="$1"
    local line
    local -a details=()

    while IFS= read -r line; do
        local type pkname part_name part_uuid part_mount
        type="$(extract_kv "$line" "TYPE")"
        pkname="$(extract_kv "$line" "PKNAME")"
        [ "$type" = "part" ] || continue
        [ "$pkname" = "$disk_name" ] || continue

        part_name="$(extract_kv "$line" "NAME")"
        part_uuid="$(extract_kv "$line" "UUID")"
        part_mount="$(extract_kv "$line" "MOUNTPOINT")"
        details+=("/dev/${part_name}|${part_uuid:-none}|${part_mount:-not-mounted}")
    done < <(lsblk -P -o NAME,TYPE,UUID,MOUNTPOINT,PKNAME)

    printf '%s\n' "${details[@]}"
}

udev_props_for_block_disk() {
    local disk_name="$1"
    local sysfs_path
    sysfs_path="$(udevadm info -q path -p "/sys/class/block/${disk_name}" 2>/dev/null || true)"
    [ -n "$sysfs_path" ] || return 1
    udevadm info --query=property --path "$sysfs_path" 2>/dev/null || true
}

append_device() {
    local key="$1"
    local label="$2"
    local strategy="$3"
    local match_value="$4"
    local note="$5"
    local rule_count="$6"
    local kind="$7"

    DEVICE_KEYS+=("$key")
    DEVICE_LABELS+=("$label")
    DEVICE_STRATEGIES+=("$strategy")
    DEVICE_MATCH_VALUES+=("$match_value")
    DEVICE_RULE_NOTES+=("$note")
    DEVICE_RULE_COUNTS+=("$rule_count")
    DEVICE_KINDS+=("$kind")
}

is_phone_or_media_candidate() {
    local manufacturer="$1"
    local product="$2"
    local lower
    lower="$(lowercase "${manufacturer} ${product}")"

    [[ "$lower" =~ iphone|ipad|ipod|android|phone|pixel|galaxy|mtp ]]
}

discover_usb_storage_devices() {
    local line
    while IFS= read -r line; do
        local type disk_name disk_path transport size
        type="$(extract_kv "$line" "TYPE")"
        [ "$type" = "disk" ] || continue

        disk_name="$(extract_kv "$line" "NAME")"
        disk_path="/dev/${disk_name}"
        transport="$(extract_kv "$line" "TRAN")"
        size="$(extract_kv "$line" "SIZE")"

        local props id_bus vendor model serial_short serial vendor_id model_id
        props="$(udev_props_for_block_disk "$disk_name")"
        id_bus="$(awk -F= '$1 == "ID_BUS" { print $2 }' <<< "$props")"

        if [ "$transport" != "usb" ] && [ "$id_bus" != "usb" ]; then
            continue
        fi

        vendor="$(awk -F= '$1 == "ID_VENDOR" { print $2 }' <<< "$props")"
        model="$(awk -F= '$1 == "ID_MODEL" { print $2 }' <<< "$props")"
        serial_short="$(awk -F= '$1 == "ID_SERIAL_SHORT" { print $2 }' <<< "$props")"
        serial="$(awk -F= '$1 == "ID_SERIAL" { print $2 }' <<< "$props")"
        vendor_id="$(awk -F= '$1 == "ID_VENDOR_ID" { print $2 }' <<< "$props")"
        model_id="$(awk -F= '$1 == "ID_MODEL_ID" { print $2 }' <<< "$props")"

        local display_name label strategy match_value note rule_count
        display_name="$(trim_spaces "${vendor//_/ } ${model//_/ }")"
        [ -n "$display_name" ] || display_name="USB storage device"
        label="${display_name} ${size} (${disk_path})"
        note=""
        rule_count="1"

        if [ -n "$serial_short" ]; then
            strategy="serial_short"
            match_value="$serial_short"
            note="USB storage device. Blocks desktop automount by disk serial."
        elif [ -n "$serial" ]; then
            strategy="serial"
            match_value="$serial"
            note="USB storage device. Blocks desktop automount by full serial."
        else
            local partition_uuid_csv=""
            local partition_line part_uuid
            while IFS= read -r partition_line; do
                [ -n "$partition_line" ] || continue
                part_uuid="$(cut -d'|' -f2 <<< "$partition_line")"
                [ "$part_uuid" != "none" ] || continue
                if [ -n "$partition_uuid_csv" ]; then
                    partition_uuid_csv="${partition_uuid_csv},${part_uuid}"
                else
                    partition_uuid_csv="${part_uuid}"
                fi
            done < <(collect_partition_details "$disk_name")

            if [ -n "$partition_uuid_csv" ]; then
                strategy="fs_uuid"
                match_value="$partition_uuid_csv"
                rule_count="$(awk -F',' '{ print NF }' <<< "$partition_uuid_csv")"
                note="USB storage device. No serial found, so partition UUIDs are used."
            elif [ -n "$vendor_id" ] && [ -n "$model_id" ]; then
                strategy="vendor_model"
                match_value="${vendor_id}|${model_id}"
                note="USB storage device. Broad fallback using vendor/model IDs."
            else
                continue
            fi
        fi

        append_device \
            "${strategy}:${match_value}" \
            "$label" \
            "$strategy" \
            "$match_value" \
            "$note" \
            "$rule_count" \
            "storage"
    done < <(lsblk -P -o NAME,TYPE,SIZE,TRAN)
}

discover_usb_phone_devices() {
    local sys_device
    for sys_device in /sys/bus/usb/devices/*; do
        [ -f "$sys_device/idVendor" ] || continue

        local manufacturer product serial vendor_id product_id devname
        manufacturer="$(read_sys_attr "$sys_device/manufacturer")"
        product="$(read_sys_attr "$sys_device/product")"
        serial="$(read_sys_attr "$sys_device/serial")"
        vendor_id="$(read_sys_attr "$sys_device/idVendor")"
        product_id="$(read_sys_attr "$sys_device/idProduct")"
        devname="$(basename "$sys_device")"

        [ -n "$vendor_id" ] || continue
        [ -n "$product_id" ] || continue
        is_phone_or_media_candidate "$manufacturer" "$product" || continue

        local display_name label match_value note key
        display_name="$(trim_spaces "${manufacturer} ${product}")"
        [ -n "$display_name" ] || display_name="USB phone/media device"
        label="${display_name} (${devname})"
        match_value="${vendor_id}|${product_id}|${serial}"
        key="media_probe:${match_value}"
        note="Phone/media device. Best-effort block for MTP, photo import, and iPhone browse prompts."

        append_device \
            "$key" \
            "$label" \
            "media_probe" \
            "$match_value" \
            "$note" \
            "1" \
            "media"
    done
}

discover_devices() {
    DEVICE_KEYS=()
    DEVICE_LABELS=()
    DEVICE_STRATEGIES=()
    DEVICE_MATCH_VALUES=()
    DEVICE_RULE_NOTES=()
    DEVICE_RULE_COUNTS=()
    DEVICE_KINDS=()

    discover_usb_storage_devices
    discover_usb_phone_devices
}

show_discovered_devices() {
    discover_devices
    print_header "Connected USB Devices"

    if [ "${#DEVICE_KEYS[@]}" -eq 0 ]; then
        print_info "No supported USB storage or phone/media devices were found."
        return 0
    fi

    local i
    for i in "${!DEVICE_KEYS[@]}"; do
        printf '[%d] %s\n' "$((i + 1))" "${DEVICE_LABELS[$i]}"
        printf '    Kind: %s\n' "${DEVICE_KINDS[$i]}"
        printf '    Match: %s\n' "${DEVICE_STRATEGIES[$i]}"
        printf '    Note: %s\n' "${DEVICE_RULE_NOTES[$i]}"
        if [ "${DEVICE_STRATEGIES[$i]}" = "fs_uuid" ]; then
            printf '    UUIDs: %s\n' "${DEVICE_MATCH_VALUES[$i]}"
        else
            printf '    Value: %s\n' "${DEVICE_MATCH_VALUES[$i]}"
        fi
    done
}

parse_selection() {
    local input="$1"
    tr ', ' '\n\n' <<< "$input" | awk 'NF { print }'
}

block_selected_devices() {
    ensure_config
    discover_devices

    if [ "${#DEVICE_KEYS[@]}" -eq 0 ]; then
        print_info "No supported USB storage or phone/media devices were found."
        return 0
    fi

    show_discovered_devices
    printf '\nSelect one or more devices to block (example: 1 3 4): '

    local input choice idx
    read -r input
    [ -n "${input// /}" ] || die "No selection provided."

    while IFS= read -r choice; do
        idx=$((choice - 1))
        [ "$idx" -ge 0 ] 2>/dev/null || die "Invalid selection: $choice"
        [ "$idx" -lt "${#DEVICE_KEYS[@]}" ] || die "Invalid selection: $choice"

        if device_exists_in_blocklist "${DEVICE_KEYS[$idx]}"; then
            print_info "Already blocked: ${DEVICE_LABELS[$idx]}"
            continue
        fi

        append_blocklist_record \
            "${DEVICE_KEYS[$idx]}" \
            "${DEVICE_LABELS[$idx]}" \
            "${DEVICE_STRATEGIES[$idx]}" \
            "${DEVICE_MATCH_VALUES[$idx]}" \
            "${DEVICE_RULE_COUNTS[$idx]}" \
            "${DEVICE_RULE_NOTES[$idx]}"

        print_info "Blocked for automount: ${DEVICE_LABELS[$idx]}"
    done < <(parse_selection "$input")

    install_rules
}

show_blocked_devices() {
    ensure_config
    print_header "Blocked USB Devices"

    local count=0
    while IFS=$'\t' read -r key label strategy match_value rule_count note; do
        count=$((count + 1))
        printf '[%d] %s\n' "$count" "$label"
        printf '    Match: %s\n' "$strategy"
        printf '    Rules: %s\n' "$rule_count"
        printf '    Note: %s\n' "$note"
    done < <(read_blocklist_records)

    if [ "$count" -eq 0 ]; then
        print_info "No blocked devices."
    fi
}

unblock_devices() {
    ensure_config

    local -a records=()
    mapfile -t records < <(read_blocklist_records)

    if [ "${#records[@]}" -eq 0 ]; then
        print_info "No blocked devices."
        return 0
    fi

    show_blocked_devices
    printf '\nSelect one or more blocked entries to remove (example: 1 2): '

    local input choice idx
    read -r input
    [ -n "${input// /}" ] || die "No selection provided."

    local -A remove_map=()
    while IFS= read -r choice; do
        idx=$((choice - 1))
        [ "$idx" -ge 0 ] 2>/dev/null || die "Invalid selection: $choice"
        [ "$idx" -lt "${#records[@]}" ] || die "Invalid selection: $choice"
        remove_map["$idx"]=1
    done < <(parse_selection "$input")

    local temp_file
    temp_file="$(mktemp)"
    printf '# key\tlabel\tstrategy\tmatch_value\trule_count\tnote\n' > "$temp_file"

    local i
    for i in "${!records[@]}"; do
        if [ -n "${remove_map[$i]:-}" ]; then
            print_info "Unblocked: $(cut -f2 <<< "${records[$i]}")"
            continue
        fi
        printf '%s\n' "${records[$i]}" >> "$temp_file"
    done

    mv "$temp_file" "$BLOCKLIST_FILE"
    install_rules
}

show_menu() {
    cat <<'EOF'
1. List connected USB devices
2. Block selected devices from automount
3. Show blocked devices
4. Unblock selected devices
5. Rebuild udev rules from local blocklist
6. Exit
EOF
}

interactive_menu() {
    while true; do
        print_header "USB Mount Blocker"
        show_menu
        printf '\nChoose an option: '

        local choice
        read -r choice

        case "$choice" in
            1) show_discovered_devices ;;
            2) block_selected_devices ;;
            3) show_blocked_devices ;;
            4) unblock_devices ;;
            5) install_rules ;;
            6) exit 0 ;;
            *) print_info "Invalid option." ;;
        esac
    done
}

show_help() {
    cat <<EOF
Usage: $(basename "$0") [command]

Commands:
  menu       Interactive mode (default)
  list       Show connected USB storage and phone/media devices
  block      Choose one or more connected USB devices and block automount or media probing
  blocked    Show blocked devices
  unblock    Choose blocked devices to remove from the blocklist
  rebuild    Rebuild and install udev rules from the saved blocklist
  help       Show this help

Local state:
  $BLOCKLIST_FILE

Generated system rules:
  $RULES_FILE
  $MEDIA_RULES_FILE
EOF
}

main() {
    require_commands

    local command="${1:-menu}"
    case "$command" in
        menu)
            ensure_config
            interactive_menu
            ;;
        list) show_discovered_devices ;;
        block)
            ensure_config
            block_selected_devices
            ;;
        blocked)
            ensure_config
            show_blocked_devices
            ;;
        unblock)
            ensure_config
            unblock_devices
            ;;
        rebuild)
            ensure_config
            install_rules
            ;;
        help|-h|--help) show_help ;;
        *) die "Unknown command: $command" ;;
    esac
}

main "$@"
